# Generated by Django 5.0.3 on 2024-04-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50, unique=True)),
                ('plan_code', models.CharField(max_length=50, unique=True)),
                ('no_books', models.IntegerField(unique=True)),
                ('return_period', models.IntegerField(unique=True)),
                ('plan_rate', models.IntegerField(unique=True)),
            ],
        ),
    ]
