# Generated by Django 5.0.3 on 2024-05-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership_plan',
            name='fine_amount',
            field=models.IntegerField(default=10),
        ),
    ]
