# Generated by Django 5.0.3 on 2024-05-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ('created_at',)},
        ),
    ]
