# Generated by Django 5.0.3 on 2024-04-21 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpay_backend', '0003_membership_payment_status_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='membership_payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='razorpay_backend.membership_payment'),
        ),
    ]
