# Generated by Django 5.0.3 on 2024-04-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razorpay_backend', '0004_transaction_membership_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership_payment',
            name='membership_plan',
        ),
    ]
