# Generated by Django 5.0.3 on 2024-04-21 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('razorpay_backend', '0005_remove_membership_payment_membership_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership_payment',
            name='membership_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_plan_id', to='membership.membership_plan'),
        ),
    ]
