# Generated by Django 5.0.3 on 2024-05-22 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0008_alter_finepayment_borrow'),
        ('razorpay_backend', '0008_alter_membership_payment_patron'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fine_payment',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fine_payment', to='borrow.finepayment'),
        ),
    ]
