# Generated by Django 5.0.3 on 2024-05-22 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0008_alter_finepayment_borrow'),
        ('razorpay_backend', '0009_transaction_fine_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fine_payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fine_payment', to='borrow.finepayment'),
        ),
    ]
