# Generated by Django 5.0.3 on 2024-04-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patron',
            name='otp',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patron',
            name='otp_expire',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
