# Generated by Django 5.0.3 on 2024-04-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_patron_is_email_verified_patron_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='otp_expire',
            field=models.DateTimeField(null=True),
        ),
    ]
