# Generated by Django 5.0.3 on 2024-04-25 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_alter_patron_otp_alter_patron_otp_expire'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='membership_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='membership.membership_plan'),
        ),
    ]
