# Generated by Django 5.0.3 on 2024-04-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_author_firstname_remove_author_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_name',
        ),
        migrations.AddField(
            model_name='author',
            name='firstname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='lastname',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
