# Generated by Django 5.0.3 on 2024-04-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_author_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_variant',
            name='isbn',
            field=models.BigIntegerField(null=True),
        ),
    ]
