# Generated by Django 5.0.3 on 2024-05-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_category_alter_book_variant_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_variant',
            name='price',
            field=models.BigIntegerField(default=100, null=True),
        ),
    ]
