# Generated by Django 5.0.3 on 2024-05-06 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_category_alter_book_variant_language_and_more'),
        ('borrow', '0003_remove_borrow_renewal_count_borrow_renewal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_book', to='book.book_variant'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_patron', to=settings.AUTH_USER_MODEL),
        ),
    ]
