# Generated by Django 5.0.3 on 2024-05-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0005_fine_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fine_payment',
            new_name='FinePayment',
        ),
    ]
