# Generated by Django 5.0.3 on 2024-05-21 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0006_rename_fine_payment_finepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finepayment',
            name='borrow',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrow.borrow'),
        ),
    ]
